# Generated by Django 4.2.1 on 2023-05-28 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kino', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='email',
        ),
        migrations.AddField(
            model_name='comment',
            name='score',
            field=models.IntegerField(default=7),
            preserve_default=False,
        ),
    ]
