# Generated by Django 4.2.1 on 2023-06-04 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kino', '0003_comment_movie_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='seat_nr',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='ticket',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
