# Generated by Django 4.2.1 on 2023-06-04 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kino', '0004_ticket_seat_nr_alter_ticket_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='price',
        ),
        migrations.AddField(
            model_name='repertoire',
            name='price',
            field=models.IntegerField(default=25),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='repertoire',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
