# Generated by Django 4.2.1 on 2023-06-06 20:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kino', '0005_remove_ticket_price_repertoire_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='movie_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kino.movie'),
        ),
        migrations.AlterField(
            model_name='repertoire',
            name='movie_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kino.movie'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='movie_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kino.repertoire'),
        ),
    ]
