# Generated by Django 4.2.1 on 2023-06-10 16:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kino', '0008_director_genre_delete_news_remove_movie_genre'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='director_id',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='kino.director'),
        ),
        migrations.AddField(
            model_name='movie',
            name='genre_id',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='kino.genre'),
        ),
    ]
