# Generated by Django 4.2.1 on 2023-06-10 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kino', '0009_movie_director_id_movie_genre_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='pub_date',
            field=models.DateField(verbose_name='released date'),
        ),
    ]
